### ISSUE TITLE
Control the width?

### ISSUE THREAD

**Issue by bernpuc** [datavisyn/chartjs-chart-boxplot#2]
Is there a way to control the width of the box? I want a sleeker looking box.
Thanks.

**Comment by bernpuc** [comment]
Ach. Nevermind, I just realized its probably like a bar chart - and it is. Thanks for the great library BTW.

**Comment by sgratzl** [comment]
yes, internally it is based on the Bar Controller from Chart.js. 

see 

https://github.com/chartjs/Chart.js/blob/master/src/controllers/controller.bar.js#L244-L259

But it could also be a useful extension for Chart.js itself

**Comment by sgratzl** [comment]
there is a new `padding` option available. When the value is between 0 and 1 it will be interpreted as percent, > 1 as pixel. e.g. 0.5 reduces the box with by 50%;
