### ISSUE TITLE
Min=Max tooltip missing

### ISSUE THREAD

**Issue by nicdutil** [datavisyn/chartjs-chart-boxplot#21]
Thanks for this very nice extension.

Ive got a data series where, for a given data point, min=max is a possibility. In such case, I see a single whisker and cannot  get a tooltip to display when hovering over the whisker. It works fine for all the other data points in my series where min != max.  Seems like I should at least be able to get a tooltip when hovering over any of my data points even when its a single whisker (min=max case). 

If there is a workaround or a way to fix this, it'd be appreciated. 

Thanks!

**Comment by sgratzl** [comment]
example illustrating the issue: https://codepen.io/sgratzl/pen/PxWPZZ?editors=0010

**Comment by sgratzl** [comment]
fixed with v1.1.2 -> see updated https://codepen.io/sgratzl/pen/PxWPZZ?editors=0010

**Comment by nicdutil** [comment]
That was quick! 
Thank you. much appreciated.
